<a href="https://colab.research.google.com/github/Arifbinmushtaq/Arifbinmushtaq/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [4]:
n1=np.array([10,20,30,40])    #1d array
n1

array([10, 20, 30, 40])

In [6]:
n2=np.array([[100,200,300,],[100,300,600]])  #2d array
n2

array([[100, 200, 300],
       [100, 300, 600]])

In [7]:
a=np.array([1,3,5])
b=np.array([1,2,3])
a*b

array([ 1,  6, 15])

In [12]:
a=np.array([2,3,6])
b=np.array([6,2,1])
a*b

array([12,  6,  6])

In [9]:
a+b

array([8, 5, 7])

In [10]:
a/b

array([0.33333333, 1.5       , 6.        ])

In [11]:
a%b

array([2, 1, 0])

In [13]:
a=np.array([1,2,3],'int32')
a

array([1, 2, 3], dtype=int32)

In [14]:
#get dimension
a.ndim


1

In [16]:
#get shape
a.shape


(3,)

In [18]:
#get type
a.dtype

dtype('int32')

In [21]:
#get size
a.itemsize

4

In [25]:
#get total size
a.nbytes

12

In [28]:
a=np.array([[1,2,3,4,5,6,7,8,],[8,9,10,11,1,2,12,14,15]])
(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3, 4, 5, 6, 7, 8]),
       list([8, 9, 10, 11, 1, 2, 12, 14, 15])], dtype=object)

In [31]:
#get specific element[r,c]
a[1]


[8, 9, 10, 11, 1, 2, 12, 14, 15]

In [34]:
a[0]

[1, 2, 3, 4, 5, 6, 7, 8]

In [36]:
#get a specific column
a[1]

[8, 9, 10, 11, 1, 2, 12, 14, 15]

In [42]:
a[0]


[1, 2, 3, 4, 5, 6, 7, 8]

In [45]:
b=np.array([[[1,2],[3,4]],[[5,9],[7,8,9]]])
b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([[list([1, 2]), list([3, 4])],
       [list([5, 9]), list([7, 8, 9])]], dtype=object)

In [50]:
#get a specific element
b[0,1]
b[:,1]

array([list([3, 4]), list([7, 8, 9])], dtype=object)

In [51]:
b[1,:]

array([list([5, 9]), list([7, 8, 9])], dtype=object)

In [53]:
b[0:1]

array([[list([1, 2]), list([3, 4])]], dtype=object)

In [54]:
#replace
b[:,1]=[[9,9],[8,8]]
b

array([[list([1, 2]), list([9, 9])],
       [list([5, 9]), list([8, 8])]], dtype=object)

In [56]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
a[:,2]

array([3, 8])

In [58]:
a[0,2]

3

In [59]:
a[1,0]

6

In [60]:
#all zero matrix 
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [63]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [73]:
#all 1s matrix 
np.ones((4,2,21))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.]]])

In [74]:
np.ones((1,1,3))

array([[[1., 1., 1.]]])

In [ ]:
#any other number