<a href="https://colab.research.google.com/github/Arifbinmushtaq/Arifbinmushtaq/blob/main/numpy%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
type(n1)

numpy.ndarray

In [8]:
n2=np.array([[1,2,3,4],[4,5,6,7]])
n2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [9]:
type(n2)

numpy.ndarray

In [10]:
#initializing numpy array with zeros 
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [12]:
import numpy as np 
n2=np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
import numpy as np
n3=np.zeros(((1,2,3)))
n3


array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
#initializing numpy array with same number
import numpy as np
n1=np.full((2,2),(10))
n1

array([[10, 10],
       [10, 10]])

In [17]:
import numpy as np
n1=np.full((5,5),(100))
n1

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [18]:
#initializing numpy as within a range 
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
import numpy as np
n2=np.arange(10,50,5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
import numpy as np
n=np.arange(100,500,100)
n

array([100, 200, 300, 400])

In [25]:
#random numbers
import numpy as np
n1=np.random.randint(1,100,5)
n1

array([18,  6, 38, 20,  1])

In [28]:
n1=np.random.randint([1,100,5])
n1

array([0, 4, 4])

In [29]:
import numpy as np 
n1=np.array(([1,2,3],[4,5,6]))
n1.shape

(2, 3)

In [30]:
#joining numpy arrays 
#vstack()
import numpy as np 
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [31]:
import numpy as np 
#hstack() 
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [33]:
import numpy as np 
#column_stack()
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
#numpy intersection and difference
import numpy as np
