<a href="https://colab.research.google.com/github/Arifbinmushtaq/Arifbinmushtaq/blob/main/numpy_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
a=np.array([1,2,3])
print(a)


[1 2 3]


In [4]:
print(a[0])
print(a[1])
print(a[2])

1
2
3


In [ ]:
#practical_02 -----------------------------------------------------------------

In [7]:
#practical 02 linear algebra
a=np.array([1.0,2.0,3.0])
print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [8]:
# to create zeros
a=np.zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#to create ones
b=np.ones([1,2,3])
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
#to create empty array 
s=np.empty([1,2])
print(s)

[[1. 1.]]


In [17]:
x=np.array([3,4,5])
print(x)

[3 4 5]


In [18]:
y=np.array([4,5,6])
print(y)

[4 5 6]


In [19]:
z = x*y
print(z)

[12 20 30]


In [20]:
z=x+y
print(z)

[ 7  9 11]


In [21]:
z=np.vstack((x,y))
print(z)

[[3 4 5]
 [4 5 6]]


In [22]:
w=np.hstack((x,y))
print(w)

[3 4 5 4 5 6]


In [23]:
#to create matrix
a=np.array([[1,2,3],[2,3,4],[1,4,9]])
print(a)

[[1 2 3]
 [2 3 4]
 [1 4 9]]


In [24]:
b = np.array([[1,4,6],[3,0,6],[6,3,2]])
print(b)

[[1 4 6]
 [3 0 6]
 [6 3 2]]


In [25]:
print(a+b)

[[ 2  6  9]
 [ 5  3 10]
 [ 7  7 11]]


In [26]:
print(a*b)

[[ 1  8 18]
 [ 6  0 24]
 [ 6 12 18]]


In [27]:
print(a/b)

[[1.         0.5        0.5       ]
 [0.66666667        inf 0.66666667]
 [0.16666667 1.33333333 4.5       ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [28]:
I=np.identity(6)
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [29]:
x=np.array([[12,13,14,],[12,14,15],[18,19,20]])
print(np.tril(x))

[[12  0  0]
 [12 14  0]
 [18 19 20]]


In [31]:
print(np.triu(x))

[[12 13 14]
 [ 0 14 15]
 [ 0  0 20]]


In [32]:
D=np.array([[1,2,3],[1,3,5],[1,9,6]])
print(D)

[[1 2 3]
 [1 3 5]
 [1 9 6]]


In [34]:
d=np.diag(D)
print(D)
M=np.diag(d)
print(M)

[[1 2 3]
 [1 3 5]
 [1 9 6]]
[[1 0 0]
 [0 3 0]
 [0 0 6]]


In [35]:
#transpose of matrix
a=np.array([[1,2,3],[1,5,9],[1,0,5]])
print(a)


[[1 2 3]
 [1 5 9]
 [1 0 5]]


In [36]:
print(a.T)

[[1 1 1]
 [2 5 0]
 [3 9 5]]


In [37]:
#inverse 
a=np.array([[11,2,9],[17,8,0],[14,0,16]])
print(a)


[[11  2  9]
 [17  8  0]
 [14  0 16]]


In [38]:
b=np.linalg.inv(a)
print(b)

[[-0.88888889  0.22222222  0.5       ]
 [ 1.88888889 -0.34722222 -1.0625    ]
 [ 0.77777778 -0.19444444 -0.375     ]]


In [40]:
#orthogonal
a=np.array([[1,2,3],[1,1,1],[0,0,0]])
R=a.T
print(a)
print(R)
I=a.dot(R)
print(I)

[[1 2 3]
 [1 1 1]
 [0 0 0]]
[[1 1 0]
 [2 1 0]
 [3 1 0]]
[[14  6  0]
 [ 6  3  0]
 [ 0  0  0]]


In [43]:
#matrix determinant 
a=np.array(([1,2,3],[1,7,9],[1,9,2]))
print(a)
b=np.linalg.det(a)
print(b)

[[1 2 3]
 [1 7 9]
 [1 9 2]]
-46.99999999999999


In [47]:
#rank
v=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(v)
v = np.linalg.matrix_rank(v)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [49]:
#trace
a=np.array([[11,23,6],[1,2,6],[1,1,1]])
print(a)
s=np.trace(a)
print(s)

[[11 23  6]
 [ 1  2  6]
 [ 1  1  1]]
14
